// Renders a <picture> that prefers WebP (generated by scripts/optimize-images.mjs)
// and falls back to the original JPG/PNG. Drop-in replacement for <img>;
// any extra props (data-reveal, style, fetchpriority…) pass through to <img>.
export default function Picture({
  src, alt, className, width, height,
  loading = 'lazy', sizes, ...rest
}) {
  const webp = src.replace(/\.(jpe?g|png)$/i, '.webp');
  const hasWebp = webp !== src;
  return (
    <picture>
      {hasWebp && <source srcSet={webp} type="image/webp" sizes={sizes} />}
      <img
        src={src}
        alt={alt}
        className={className}
        width={width}
        height={height}
        loading={loading}
        decoding="async"
        {...rest}
      />
    </picture>
  );
}
